services:
  web:
    build: ./src/backend

    command: sh -c "python /app/backend/manage.py migrate && python /app/backend/manage.py collectstatic --noinput && daphne -e ssl:443:privateKey=/etc/ssl/certs/privkey.pem:certKey=/etc/ssl/certs/fullchain.pem backend.websocket_demo.asgi:application"

    volumes:
      - ./src:/app # Mount the entire src directory
      - /etc/letsencrypt/live/django.sldunit.xyz:/etc/ssl/certs # Mounting SSL symbolic links
      - /etc/letsencrypt/archive/django.sldunit.xyz:/etc/letsencrypt/archive/django.sldunit.xyz # Mount actual certificate files
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - redis
    environment:
      - Debug=False
      - REDIS_URL=redis://redis:6379/1
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SECRET_KEY=${SECRET_KEY}
      - ENVIRONMENT=${ENVIRONMENT}
  redis:
    image: "redis:7"
    ports:
      - "6379:6379"
