services:
  web:
    build: ./src/backend
    # command: sh -c "python manage.py migrate && daphne -b 0.0.0.0 -p 443 --ssl-key /etc/ssl/certs/privkey.pem --ssl-cert /etc/ssl/certs/fullchain.pem websocket_demo.asgi:application"
    command: sh -c "python manage.py migrate && daphne -e ssl:443:privateKey=/etc/ssl/certs/privkey.pem:certKey=/etc/ssl/certs/fullchain.pem websocket_demo.asgi:application"

    volumes:
      - ./src/backend:/app
      - /etc/letsencrypt/live/django.sldunit.xyz:/etc/ssl/certs # Mounting SSL symbolic links
      - /etc/letsencrypt/archive/django.sldunit.xyz:/etc/letsencrypt/archive/django.sldunit.xyz # Mount actual certificate files

    ports:
      # if we will use NGINX as a reserve proxy and for the static files, then Daphne will be on port 8000
      # - "8000:8000"
      # - "80:80"
      - "443:443"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/1
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}

  redis:
    image: "redis:7"
    ports:
      - "6379:6379"
