services:
  web:
    build: ./src/backend
    command: sh -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 websocket_demo.asgi:application"
    volumes:
      - ./src/backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/1
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}

  redis:
    image: "redis:7"
    ports:
      - "6379:6379"
